<div class ="col-sm-12" style="padding:25px 15px 50px 20px">
<h2> Sejarah PT. Aruna Wijaya Sakti (Sekarang)</h2>
	<p style="text-align:justify;"><img src="img/aruna.jpg" height="40%" width="40%" style="float:right;margin:0 0 4px 8px;"></p>
		<p style="text-align:justify;"> &nbsp &nbsp&nbsp Bumi dipasena adalah hamparan lahan yang tadinya hutan rawa rawa bertanah gambut dan sunyi. Tidak ada penduduk yang bermukim disana karena masih banyak binatang buas yang berbahaya. Ada buaya, ular, harimau bahkan gajah liar pun dulunya banyak disana.	</p>
		<p style="text-align:justify;"><img src="img/tambak.jpg" height="30%" width="30%" style="float:left;margin:0 8px 4px 0;">&nbsp &nbsp&nbsp Seiring laju perkembangan zaman, area ini dibuka oleh pengusaha dijadikan ribuan hektar lahan tambak udang dan dijadikan ribuan petak tambak lengkap dengan sarana penunjang budidaya udang pola intensif yang konon terbesar di Asia. Bukan hanya jumlah petak tambak yang banyak saja, tapi disana juga berdiri power house, coldstorage, pabrik pakan udang, workshop, pelabuhan export,	medical, perkantoran yang elit, dan masih banyak lagi sarana sosial dan ekonomi yang lengkap. Ribuan orang menggantungkan hidupnya dari bekerja di area yang terkenal dengan sebutan Dipasena itu, baik sebagai petambak udang, karyawan perusahaan, atau usaha yang lain. Disinyalir ada uang ratusan milyard rupiah berputar disana tiap bulan. Pada awalnya yang membuka lahan itu adalah PT.DIPASENA CITRA DHARMAJA (PT.DCD) pada awal tahun 90an.</p>
		<p style="text-align:justify;"> &nbsp &nbsp&nbsp Dan pada masa kejayaannya pt.dcd mampu mengexport udang windu kwalitas terbaik dengan jumlah ribuan ton. Sangat besar keuntungan yang diperoleh para petambak udang yang bekerja sama dengan pt.dcd dengan pola kemitraan inti-plasma itu. Tapi sayang, itu tidak bertahan lama. Bukan karena lahan yang tidak subur lagi atau faktor alam lainnya. Tapi karena petambak sebagai plasma dan perusahaan sebagai inti tidak bisa bekerja sama secara harmonis lagi. Perusahaan semakin arogan dengan nama besarnya, dan petambak mulai menuntut haknya, karena petambak sebagai ujung tombak keberhasilan itu merasa dirugikan. Akhirnya terjadi demo besar besaran dan tumbanglah pt.dcd.</p>
		<p style="text-align:justify;"><img src="img/panen.jpg" height="30%" width="30%" style="float:left;margin:0 8px 4px 0;">&nbsp &nbsp&nbsp Setelah pt.dcd gagal dan tidak divalidasi oleh pemerintah, petambak plasma seperti anak ayam kehilangan induk. Berusaha budidaya udang sendiri secara mandiri walau hasilnya tidak memuaskan. Dengan modal yang minim akhirnya petambak plasma tidak bisa lagi menggantungkan hidup dengan budidaya udang, tapi mulai memanfaatkan fasilitas yang ada, memasang jaring atau bubu penangkap udang di kanal outlet yang seharusnya sebagai sarana transportasi, dan bahkan memasang berbagai alat penangkap udang di kanal inlet yang seharusnya tidak boleh dicemari dengan alat apapun atau dengan cara apapun karena kanal inlet adalah kanal yang mendistribusikan air laut ke petak tambak budidaya. Karena air yang seharusnya dijaga malah dicemari, hasil budidaya petambak mulai turun drastis. Ditengah kesulitan itu petambak menanti tindakan pemerintah untuk cepat menangani kasus ini. Beberapa kali pemerintah mendatangkan investor tapi tetap saja belum ada yang mampu.</p>
		<p style="text-align:justify;"> &nbsp &nbsp&nbsp Pada akhir tahun 2007 aset eks pt.dcd dijual oleh pemerintah ke PT.ARUNA WIJAYA SAKTI, anak perusahaan PT.CENTRA PROTEINA PRIMA (PT.CPP). Pada awalnya gebrakan pt.aws meyakinkan para petambak, mencanangkan program revitalisasi menyeluruh yang di agendakan selesai akhir tahun 2009. Tapi kenyataan nya sampai oktober 2009 baru 5 blok yang direvit, dan 11 blok lagi belum direvit. Ini yang memicu petambak melakukan aksi demo di coldstorage pt.aws dan demo di kantor bupati tulangbawang. Para petambak mulai gelisah lagi, mereka khawatir kalau pt.aws nggak jauh beda dengan pt.dcd. Mereka khawatir Kalau proyek ini tidak bisa dijalankan dengan benar maka bukan hanya petambak yang dirugikan, tetapi seluruh rakyat indonesia, karena membangun mega proyek ini ternyata pakai uang rakyat juga.</p>
		<p style="text-align:justify;">&nbsp &nbsp&nbsp Alat Transportasi yang bisa masuk ke daerah dipasena hanyalah kendaraan roda dua dan kendaraan air, karena harus menyebrangi kanal yang lebarnya mencapai 60 meter menggunakan perahu yang biasa petani udang menyebutnya ponton. Dengan demikian akan sulit mengakses jalur untuk kesana apabila menggunakan kendaraan roda 4.</p>
		
		<p> &nbsp &nbsp&nbsp </p>

</div>